import React from 'react'
import { ShieldAlert } from 'lucide-react'

/**
 * Reusable disclaimer banner. `compact` renders a smaller inline version
 * suitable for results pages; the default is the fuller home/about version.
 */
export default function Disclaimer({ compact = false }) {
  if (compact) {
    return (
      <div className="flex items-start gap-3 rounded-2xl border border-accent-100 bg-accent-50/60 p-4">
        <ShieldAlert size={18} className="mt-0.5 shrink-0 text-accent-600" />
        <p className="text-sm leading-relaxed text-slate-600">
          <span className="font-semibold text-slate-800">Not a medical diagnosis.</span>{' '}
          This result is generated by an AI research model for educational purposes.
          Please consult a qualified medical professional for any health concerns.
        </p>
      </div>
    )
  }

  return (
    <div className="rounded-3xl border border-accent-100 bg-gradient-to-br from-accent-50/70 to-primary-50/60 p-6 sm:p-8">
      <div className="flex items-start gap-4">
        <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-white text-accent-600 shadow-softer">
          <ShieldAlert size={20} />
        </span>
        <div>
          <h3 className="font-display text-base font-semibold text-slate-900">
            Medical disclaimer
          </h3>
          <p className="mt-1.5 max-w-2xl text-sm leading-relaxed text-slate-600">
            NeuroScan AI is built for educational and research purposes only. Its
            predictions are not a medical diagnosis and should never replace
            professional medical advice, evaluation, or treatment. Always consult a
            qualified radiologist or physician about any MRI scan or health concern.
          </p>
        </div>
      </div>
    </div>
  )
}
